# Generated by Django 5.1 on 2024-08-24 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('cli_id', models.AutoField(primary_key=True, serialize=False)),
                ('cli_nombre', models.CharField(max_length=255)),
                ('cli_telefono', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('emp_id', models.AutoField(primary_key=True, serialize=False)),
                ('emp_nombre', models.CharField(max_length=255)),
                ('emp_direccion', models.CharField(max_length=255)),
                ('emp_telefono', models.CharField(max_length=20)),
                ('emp_email', models.EmailField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Empresas',
            },
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('cta_id', models.AutoField(primary_key=True, serialize=False)),
                ('cta_duracion', models.IntegerField()),
                ('cta_fecha_hora', models.DateTimeField()),
                ('cta_imagen', models.ImageField(blank=True, null=True, upload_to='citas/')),
                ('cta_cli', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agenda.cliente')),
            ],
            options={
                'verbose_name_plural': 'Citas',
            },
        ),
        migrations.CreateModel(
            name='Negocio',
            fields=[
                ('neg_id', models.AutoField(primary_key=True, serialize=False)),
                ('neg_nombre', models.CharField(max_length=255)),
                ('neg_tipo', models.CharField(max_length=255)),
                ('neg_direccion', models.CharField(max_length=255)),
                ('neg_telefono', models.CharField(max_length=20)),
                ('neg_email', models.EmailField(max_length=255)),
                ('neg_emp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agenda.empresa')),
            ],
            options={
                'verbose_name_plural': 'Negocios',
            },
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('ntf_id', models.AutoField(primary_key=True, serialize=False)),
                ('ntf_mensaje', models.TextField()),
                ('ntf_fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('ntf_cli', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agenda.cliente')),
                ('ntf_cta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agenda.cita')),
            ],
            options={
                'verbose_name_plural': 'Notificaciones',
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('srv_id', models.AutoField(primary_key=True, serialize=False)),
                ('srv_nombre', models.CharField(max_length=255)),
                ('srv_descripcion', models.TextField()),
                ('srv_neg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agenda.negocio')),
            ],
            options={
                'verbose_name_plural': 'Servicios',
            },
        ),
        migrations.AddField(
            model_name='cita',
            name='cta_srv',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agenda.servicio'),
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('usu_id', models.AutoField(primary_key=True, serialize=False)),
                ('usu_nombre', models.CharField(max_length=255)),
                ('usu_telefono', models.CharField(max_length=20)),
                ('usu_email', models.EmailField(max_length=255)),
                ('srv_neg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agenda.negocio')),
            ],
            options={
                'verbose_name_plural': 'Usuarios',
            },
        ),
    ]
